export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed-dim": "#4cd7f6",
        "error": "#ffb4ab",
        "outline-variant": "#464554",
        "background": "#0b1326",
        "outline": "#908fa0",
        "surface-bright": "#31394d",
        "inverse-surface": "#dae2fd",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "surface-container-lowest": "#060e20",
        "on-tertiary-container": "#002f38",
        "secondary-container": "#571bc1",
        "on-secondary-fixed": "#23005c",
        "on-primary": "#1000a9",
        "on-primary-container": "#0d0096",
        "error-container": "#93000a",
        "surface": "#0b1326",
        "secondary-fixed-dim": "#d0bcff",
        "secondary-fixed": "#e9ddff",
        "inverse-on-surface": "#283044",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary": "#3c0091",
        "on-tertiary": "#003640",
        "on-surface-variant": "#c7c4d7",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-fixed": "#acedff",
        "surface-container": "#171f33",
        "surface-container-highest": "#2d3449",
        "primary-container": "#8083ff",
        "tertiary-container": "#009eb9",
        "tertiary": "#4cd7f6",
        "surface-dim": "#0b1326",
        "surface-container-high": "#222a3d",
        "primary-fixed": "#e1e0ff",
        "secondary": "#d0bcff",
        "surface-tint": "#c0c1ff",
        "surface-container-low": "#131b2e",
        "on-tertiary-fixed": "#001f26",
        "on-background": "#dae2fd",
        "on-secondary-container": "#c4abff",
        "inverse-primary": "#494bd6",
        "primary": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5516be"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "0.5rem",
        "space-sm": "0.5rem",
        "margin": "0.75rem",
        "space-lg": "1rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "space-xl": "1.25rem"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "code-sm": ["JetBrains Mono"]
      },
      "fontSize": {
        "headline-md": ["15px", { "lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "body-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "code-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
